name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Checkout ExifTool submodule
        shell: bash
        run: |
          git submodule update --init --force --recursive --depth=1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: flake8 sortphotos  --max-line-length 120 --count --show-source --statistics
      - name: Test with unittest
        run: python test_ImageCollection.py
      - name: Prepare release
        run: |
          (cd sortphotos/exiftool/ && rm -rf html/ fmt_files/ Makefile.PL META.* t validate windows_exiftool pp_build_exe.args perl-Image-ExifTool.spec config_files Changes build_tag_lookup arg_files)
          zip -r sortphotos.zip example.png README.md sortphotos.py sortphotos
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: sortphotos.zip
